### ISSUE TITLE
allow relative dates

### ISSUE THREAD

**Issue by kra** [futel/usage#18]
eg starting 1 week ago ending today

the dates in the URLs are human readable so I don't know how necessary this is, for example JS tooling should be able to generate the desired page without adding features to the UI itself. But it would take me some work to figure that out, not sure whether this is a reasonable solution.

**Comment by breedx2** [comment]
Always some some historical period referenced to today, or also referenced to some arbitrary end date? 
I could see wanting to do things like 2022-12-31 with a period of -1y for year-to-date kind of stuff.

**Comment by kra** [comment]
Historical period relative to today eg -1y, -6m.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
