### ISSUE TITLE
select scroll controls not working?

### ISSUE THREAD

**Issue by kra** [futel/usage#25]
Is this just my browser or something? I can't scroll the events or phones selects using the grabbers. I can use the arrow keys or pageup/pagedown, but I can't use the mouse. This means I can't select all phones for example, because arrows/page keys reset what is selected already.

**Comment by breedx2** [comment]
Grabbers? Like the scrollbar?
In any case, need more detail, works on my box. 
Mousewheel (or two-finger trackpad scroll) while hovered in the box scrolls vertical up/down. Grabbing the scrollbar and dragging allows up/down scrolling as well.
All phones is easy -- there's a convenient button. heh.
Normally it's a ctrl-click to select multiple/various...but I don't think that's what you're getting at.

**Comment by kra** [comment]
Yes, the scrollbar. It is not working in firefox on my machine and is working on chrome on my machine! HAW HAW HAW! I should have just tried that.
