### ISSUE TITLE
incoming line not in extensions

### ISSUE THREAD

**Issue by kra** [futel/usage#28]
is it in the data?

**Comment by breedx2** [comment]
Is it one of these? https://github.com/futel/usage/tree/gh-pages/data/channel

**Comment by kra** [comment]
crap, now I remember why this was annoying, the incoming channels are inconsistent.

I think we want "voipms",  "twilio-termination", "futel.pstn.twilio.com" and I think the two twilios are an implementation detail.

This is a few months of data, callcentric will be obsolete soon, I don't remember what the IP addresses are

```
karl@eurydice:/opt/futel/backups/prod/2022-01/var/log/asterisk/old$ sed 's/.*CHANNEL=//' metrics* | awk '{print $1}'| sed 's/-.*//'| sort | uniq -c | sort -n
      7 SIP/callcentric.com
     40 SIP/callcentric
     68 SIP/695
    117 SIP/twilio
    127 SIP/702
    138 SIP/680
    139 SIP/199.87.151.78
    150 SIP/500
    167 SIP/199.87.151.75
    199 SIP/futel.pstn.twilio.com
    234 SIP/520
    305 SIP/670
    339 SIP/505
    355 SIP/voipms
    477 SIP/640
    537 SIP/615
   1220 SIP/510
   1252 SIP/515
   1508 SIP/630
   2639 SIP/655
```

**Comment by breedx2** [comment]
I did a little tinkering, and I think that screwing with the 1:1 cardinatlity of phone <-> extension is a spreading and awful problem. We would have to either change the fundamental phone list to be one name to many extensions (just to accommodate incoming), or we would have to special case "incoming" in a bunch of places. 

Can we get by with adding 3 extensions to `phone-list.js` like `incoming1`, `incoming2`, and `incoming3` and adding a convenience button to select all incoming?
