### ISSUE TITLE
no selects on android

### ISSUE THREAD

**Issue by kra** [futel/usage#34]
can view graphs if we have a URL, but can't select anything so can't create a viewable graph or get to a viewable graph

this is low priority, I can survive without mobile and URLs that have been set up are viewable

**Comment by breedx2** [comment]
I can't imagine that the thing is mobile friendly at all tbh. There's been zero effort for that.

**Comment by breedx2** [comment]
I was able to enter data and see graphs in both Firefox and Chrome on Android by choosing the "Show Desktop Site" option. I'm not really inclined to make this very mobile friendly, so closing for now. Reopen if you think it's important again.
