### ISSUE TITLE
unusable with many selections

### ISSUE THREAD

**Issue by kra** [futel/usage#35]
maybe this is just my ancient computer? Happens for both chrome and firefox on my ubuntu box.

for example this never renders and the browse tells me the page is hanging:
relative date -1m
phones all combine phones
events all selected
aggregate weekly

**Comment by breedx2** [comment]
It seems to happen when the taylor phone is in the mix. In fact, same criteria, just taylor phone reproduces this.

**Comment by breedx2** [comment]
And it only happens with the weekly aggregation, so it's almost certainly a bug and not just a raw compute power problem. Other aggregations, daily, monthly, hourly, total all work fine.

**Comment by breedx2** [comment]
week boundary computation is not robust to handle a stray date:   "timestamp": "2022-04-05T02:31:41,612-08:00" in the taylor data.
