### ISSUE TITLE
indicate latest date in data

### ISSUE THREAD

**Issue by kra** [futel/usage#52]
When viewing I want to see how fresh the data is and also make sure that auto-refresh is working. For example if the data is updated every 4 hours, if I don't see a contact status in the last hour, I don't want to freak out because the latest event in the data is 3 hours agao.

**Comment by breedx2** [comment]
Hopefully the last updated timestamp of the s3 event files will suffice. Actually pulling the data and sifting thru it to find the latest event ts is a bit more involved/heavyweight.
