### ISSUE TITLE
graph parameters do not match URL for some events

### ISSUE THREAD

**Issue by kra** [futel/usage#71]
Create a graph
Copy the URL from the browser URL entry, see below
Paste the URL into an new browser URL entry
"dial" and "incoming-dial" is added to the events being graphed
URL in the browser URL entry is unchanged

Strangely this doesn't reproduce if the only event chosen is "wildcard-line-play-four". It does reproduce if the only event chosen is "outgoing-dialtone" or "futel-conf-dial", and the events in my URL also have "dial" substrings.

URL:

https://futel.github.io/usage/?p=680%7C640%7Cbottles-and-cans-one%7Cbottles-and-cans-two%7C415%7C410%7C420%7Ccesar-chavez%7C610%7C700%7C690%7Cdome-office%7C695%7Cghost-mountain%7C440%7Cvoipms%7Ctwilio-termination%7Cfutel.pstn.twilio.com%7Clandline%7C445%7C660%7C668%7C645%7Cr2d2%7C670%7C615%7C405%7C435%7Csjac%7C620%7Cstreet-books-one%7Cstreet-books-two%7C655%7Ctwilio%7C625%7C630&r=-1m&e=incoming-dialstatus-failed-ghost-mountain%7Cincoming-dialstatus-failed-groundscore-one%7Cincoming-dialstatus-failed-r2d2%7Cincoming-dialstatus-failed-sjac

**Comment by breedx2** [comment]
Oh yeah I think this is probably very stupid indeed. I think the pipe delimited event list isn't being split, and is then being passed into setter thing as a single string, so the substrings "dial" and "incoming-dial" are substring matching instead of checking list membership.

I think I can fix this pretty simply.

**Comment by breedx2** [comment]
Confirmed fix. You might have to force a full page refresh so that the js bundle is fetched, but it fixes this. :beers:
