### ISSUE TITLE
web ui date selector broken?

### ISSUE THREAD

**Issue by kra** [futel/usage#9]
https://futel.github.io/usage/#

When I submit a date in start: or end:, the other date is updated to match, so I can only view one day at a time.

**Comment by breedx2** [comment]
It might just be confusing/weird. I assume you're using the mouse and not entering in text, but both should work. 
It's a range picker, so when you click inside the field you get the widget to pop up. If a range is already selected it will be shown. If not, you can click the first day and then you are in a selection mode where you need to select the other day. The picker works out which one is first. 

What I suspect you're doing is maybe double clicking the day? In which case it thinks you want the same start and end date.

**Comment by kra** [comment]
yeah it was just confusing ui
